name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-18.04, ubuntu-16.04 ]
    steps:
      - name: Install the packages
        run: |
          sudo apt update
          sudo apt install -y linux-headers-$(uname -r) build-essential coreutils ipmitool libtool automake tclx  tree screen re2c darcs libreadline-dev libxt-dev x11proto-print-dev libxmu-headers libxmu-dev libxpm-dev libxmuu-dev libxmuu1 libpcre++-dev python-dev libnetcdf-dev libhdf5-dev libpng-dev libbz2-dev libxml2-dev libusb-dev libusb-1.0-0-dev libudev-dev libsnmp-dev libraw1394-dev libboost-dev libboost-regex-dev libboost-filesystem-dev libopencv-dev libtirpc-dev  libblosc-dev libtiff-dev 
          git config --global user.email "jeonghan.lee@jeonghan.com"
          git config --global user.name "jeonghanlee"
      - uses: actions/checkout@v1
      - name: Init
        run: make init
      - name: Configure
        run: |
          make conf
          make vars
      - name: Build
        run: |
          make build
          make install
      - name: Exist
        run: make exist
      - name: Check Env
        run: |
          source ${HOME}/epics-7.0.4/setEpicsEnv.bash
          caget -h
