name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, ubuntu-16.04 ]
    steps:
      - name: Install the packages
        run: |
          sudo apt update
          sudo apt install -y build-essential coreutils libtool automaketree screen re2c darcs libreadline-dev  libboost-dev libboost-regex-dev libboost-filesystem-dev libtirpc-dev libsnmp-dev
          git config --global user.email "jeonghan.lee@jeonghan.com"
          git config --global user.name "jeonghanlee"
      - uses: actions/checkout@v1
      - name: Init
        run: make init
      - name: Configure
        run: |
          make conf
          make vars
      - name: Build
        run: |
          make build
          make install
      - name: Exist
        run: make exist
      - name: Check Env
        run: |
          source ${HOME}/epics-7.0.4/setEpicsEnv.bash
          caget -h
