name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04]
    steps:
      - name: Install the packages
        run: |
          sudo apt update
          sudo apt install -y build-essential coreutils libtool automake tree screen re2c darcs libreadline-dev libboost-dev libboost-regex-dev libboost-filesystem-dev libtirpc-dev libsnmp-dev libhidapi-libusb0 libhidapi-dev libusb-1.0-0-dev libusb-1.0-0
          git config --global user.email "jeonghan.lee@jeonghan.com"
          git config --global user.name "jeonghanlee"
      - uses: actions/checkout@v1
      - name: Init
        run: make init
      - name: Configure
        run: |
          make conf
          make vars
      - name: Build
        run: |
          make build
          make install
      - name: Exist
        run: make exist
      - name: Check Env
        run: |
          make print-INSTALL_LOCATION > a
          make print-PATH_NAME_EPICS > b
          AA=$(cat a)/$(cat b)
          source ${AA}/setEpicsEnv.bash
          caget -h
