---
name: Debian 12

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/linter.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/docker-image.yml'
      - '.github/workflows/linux.yml'
      - 'docs/**'
      - 'docker/**'
  pull_request:
    branches: [master]
jobs:
  Debian12:
    runs-on: ubuntu-latest
    container: debian:bookworm-slim
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install required packages
        run: |
          apt update -y
          apt install -y git make sudo bash wget unzip
          git clone https://github.com/jeonghanlee/pkg_automation
          bash pkg_automation/pkg_automation.bash -y
          git clone https://github.com/jeonghanlee/uldaq-env
          make -C uldaq-env/ github
          git clone https://github.com/jeonghanlee/open62541-env
          make -C open62541-env/ github
      - name: EPICS installation
        run: |
          make github
          make install
      - name: EPICS Environment Check
        run: |
          make exist

