---
name: Debian 13

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/linter.yml'
      - '.github/workflows/rocky*.yml'
      - '.github/workflows/ubuntu*.yml'
      - 'docs/**'
      - 'site-template/**'

  pull_request:
    branches: [master]
jobs:
  Debian13:
    runs-on: ubuntu-latest
    container: debian:trixie-slim
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: Install required packages
        run: |
          set -e
          apt update -y
          apt install -y git make sudo bash wget unzip
          git clone https://github.com/jeonghanlee/pkg_automation
          bash pkg_automation/pkg_automation.bash -y
          VENDOR_PATH="$(make print-INSTALL_LOCATION_EPICS)/vendor"
          echo "VENDOR_ULDAQ_PATH=${VENDOR_PATH}" > configure/RELEASE.local
          echo 'OPEN62541_PATH=\$$\$$\(\_OPEN62541_CONFIG_OPCUA\)/../../../vendor' >> configure/RELEASE.local
          git clone https://github.com/jeonghanlee/uldaq-env
          echo "INSTALL_LOCATION=${VENDOR_PATH}" > uldaq-env/configure/CONFIG_SITE.local
          make -C uldaq-env/ github
          git clone https://github.com/jeonghanlee/open62541-env
          echo "INSTALL_LOCATION=${VENDOR_PATH}" > open62541-env/configure/CONFIG_SITE.local
          make -C open62541-env/ github
      - name: EPICS installation
        run: |
          make github.check
          make install
      - name: EPICS Environment Check
        run: |
          make exist
          make check.env
          make check.deps
