name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
    - '.github/workflows/docker-image.yml'
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Preparation
      run: |
        make null
        make vars
    - name: Build Docker
      run: make build.docker
