name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: Ubuntu 20.04

    steps:
    - uses: actions/checkout@v2
    - name: Preparation
      run: |
        make null
        make vars
    - name: Build Docker
      run: make build.docker
