---
name: Linter Run

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'ChangeLog.md'
  pull_request:
    branches: [master]

permissions: {}

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Lint Code Base
        uses: super-linter/super-linter@v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BASH: true
