---
name: macOS build

on:
  push:
    branches:
      - master
    paths-ignores:
      - '**.md'

jobs:
  macOS11:
    runs-on: macos-11
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install required packages
        run: |
          brew install git bash wget unzip make
          git clone https://github.com/jeonghanlee/pkg_automation
          bash pkg_automation/pkg_automation.bash -y
          brew link --force --overwrite python@3.9
          /usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip
          pip3 install numpy nose --user

      - name: EPICS Installation
        run: |
          make init
          make conf
          make vars
          make build
          make install
      - name: EPICS Environment Check
        run: |
          make exist
          source $(make print-INSTALL_LOCATION_EPICS)/setEpicsEnv.bash
          caget -h
