---
name: macOS build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/debian**.yml'
      - '.github/workflows/rocky**.yml'
      - '.github/workflows/ubuntu**.yml'
  pull_request:
    branches: [master]
jobs:
  macOS14:
    runs-on: macos-14
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11' # install the python version needed

      - name: Install required packages
        run: |
          echo 'export PATH="/usr/local/opt/net-snmp/bin:$PATH"' >> /Users/runner/.bash_profile
          echo 'export PATH="/usr/local/opt/net-snmp/sbin:$PATH"' >> /Users/runner/.bash_profile
          source /Users/runner/.bash_profile
          brew upgrade
          brew install bash wget unzip make autoconf libtool
          git clone https://github.com/jeonghanlee/pkg_automation
          bash pkg_automation/pkg_automation.bash -y
          git clone https://github.com/jeonghanlee/uldaq-env
          make -C uldaq-env/ github
        
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install numpy distutils

      - name: EPICS Installation
        run: |
          echo 'export PATH="/usr/local/opt/net-snmp/bin:$PATH"' >> /Users/runner/.bash_profile
          echo 'export PATH="/usr/local/opt/net-snmp/sbin:$PATH"' >> /Users/runner/.bash_profile
          source /Users/runner/.bash_profile
          pip install numpy disutils
          make init
          make conf
          make patch
          make vars
          make build
          make install
      - name: EPICS Environment Check
        run: |
          make exist
          source $(make print-INSTALL_LOCATION_EPICS)/setEpicsEnv.bash
          caget -h
