---
name: Rocky 8

on:
  push:
    branches: [master]
    paths-ignores:
      - '**.md'
      - '.github/workflows/linter.yml'
      - '.github/workflows/debian*.yml'
      - 'docs/**'
      - 'docker/**'
  pull_request:
    branches: [master]

jobs:
  Rocky8:
    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:8
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install required packages
        run: |
          dnf update -y
          dnf install -y git make sudo bash wget unzip
          git clone https://github.com/jeonghanlee/pkg_automation
          bash pkg_automation/pkg_automation.bash -y
          dnf install -y python3-pip
          pip3 install numpy nose
          git clone https://github.com/jeonghanlee/uldaq-env
          make -C uldaq-env/ github
      - name: EPICS installation
        run: |
          make init
          make conf
          make patch.pvxs.apply
          make vars
          make build
          make install
      - name: EPICS Environment Check
        run: |
          make exist
          make print-INSTALL_LOCATION_EPICS > a
          source $(cat a)/setEpicsEnv.bash
          caget -h
