---
name: Ubuntu 22.04

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/linter.yml'
      - '.github/workflows/debian*.yml'
      - '.github/workflows/rocky*.yml'
      - 'docs/**'
  pull_request:
    branches: [master]
jobs:
  Ubuntu22:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: Install required packages
        run: |
          set -e
          apt update -y
          apt install -y git make sudo bash wget unzip
          ln -snf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && echo "America/Los_Angeles" > /etc/timezone
          export LC_CTYPE=C.UTF-8
          export LC_ALL=C.UTF-8
          git clone https://github.com/jeonghanlee/pkg_automation
          bash pkg_automation/pkg_automation.bash -y
          VENDOR_PATH="$(make print-INSTALL_LOCATION_EPICS)/vendor"
          echo "VENDOR_ULDAQ_PATH=${VENDOR_PATH}" > configure/RELEASE.local
          echo 'OPEN62541_PATH=\$$\$$\(\_OPEN62541_CONFIG_OPCUA\)/../../../vendor' >> configure/RELEASE.local
          git clone https://github.com/jeonghanlee/uldaq-env
          echo "INSTALL_LOCATION=${VENDOR_PATH}" > uldaq-env/configure/CONFIG_SITE.local
          make -C uldaq-env/ github
          git clone https://github.com/jeonghanlee/open62541-env
          echo "INSTALL_LOCATION=${VENDOR_PATH}" > open62541-env/configure/CONFIG_SITE.local
          make -C open62541-env/ github
      - name: EPICS installation
        run: |
          make init
          make patch
          make conf
          make vars
          make build
          make install
          make symlinks
      - name: EPICS Environment Check
        run: |
          make exist
          make check.env
          make check.deps
